CREATE DATABASE vidm
COLLATE Latin1_General_CS_AS;
ALTER DATABASE vidm SET READ_COMMITTED_SNAPSHOT ON;
GO

IF NOT EXISTS
(SELECT name
FROM master.sys.server_principals
WHERE name=N'DEMO\serbl')
BEGIN
CREATE LOGIN [DEMO\serbl] FROM WINDOWS;
END
GO

USE vidm; 
IF EXISTS (SELECT * FROM sys.database_principals WHERE name=N'DEMO\Administrator')
DROP USER [DEMO\serbl]
GO

CREATE USER [DEMO\serbl] FOR LOGIN [DEMO\serbl] 
WITH DEFAULT_SCHEMA=saas;
GO

CREATE SCHEMA saas AUTHORIZATION "DEMO\serbl"
GRANT ALL ON DATABASE::vidm TO "DEMO\serbl";
GO

ALTER ROLE db_owner ADD MEMBER "DEMO\serbl";
GO